// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Byed5_gZv1LjrSqlCBxZkLycJKYU0tc',
    appId: '1:469365022703:android:f27c8a7d10974763aae01a',
    messagingSenderId: '469365022703',
    projectId: 'procrastinope-5753a',
    storageBucket: 'procrastinope-5753a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM_q6k1p9a83CKO7XEeNtHI_3vthh6sJk',
    appId: '1:469365022703:ios:7db79d4b1aec2244aae01a',
    messagingSenderId: '469365022703',
    projectId: 'procrastinope-5753a',
    storageBucket: 'procrastinope-5753a.appspot.com',
    androidClientId: '469365022703-jrlh27kpp76jc4dmu9dtnbpuvtc2pjsj.apps.googleusercontent.com',
    iosClientId: '469365022703-lksuho3plth3ngvar6phlu6h7rovj13f.apps.googleusercontent.com',
    iosBundleId: 'com.lagan.procrastinope',
  );

}